version: "3.9"
services:
  datascience-docker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/bin/bash"
    stdin_open: true
    tty: true
    container_name: datascience-docker
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    env_file:
      - .env